name: Build personal keymaps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - iris
          - gergoplex
          - cu7
    steps:
    - name: Checkout QMK
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        persist-credentials: false
        submodules: recursive
    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}
        persist-credentials: false
    - name: Build firmware
      run: qmk compile "users/${{ github.actor }}/keymaps/${{ matrix.keyboard }}.json"
    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.actor }}_firmware
        path: '*.hex'
        retention-days: 7
