name: Build personal keymaps

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        fetch-depth: 1
        persist-credentials: false
        submodules: recursive

    - uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}
        fetch-depth: 1
        persist-credentials: false

    - name: Build firmware
      run: |
          for keymap in users/${{ github.actor }}/keymaps/*.json; do
              qmk compile "$keymap" || echo "ERROR: Failed to build $keymap!"
          done
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.actor }}_firmware
        path: '*.hex'
        retention-days: 30
